/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppSolicitacoesRouteImport } from './routes/app.solicitacoes'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppNotasRouteImport } from './routes/app.notas'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppCalendarioRouteImport } from './routes/app.calendario'
import { Route as AppBibliotecaRouteImport } from './routes/app.biblioteca'
import { Route as AppDisciplinasIndexRouteImport } from './routes/app.disciplinas.index'
import { Route as AppDisciplinasIdRouteImport } from './routes/app.disciplinas.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppSolicitacoesRoute = AppSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarioRoute = AppCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinasIndexRoute = AppDisciplinasIndexRouteImport.update({
  id: '/disciplinas/',
  path: '/disciplinas/',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinasIdRoute = AppDisciplinasIdRouteImport.update({
  id: '/disciplinas/$id',
  path: '/disciplinas/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/notas': typeof AppNotasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/': typeof AppIndexRoute
  '/app/disciplinas/$id': typeof AppDisciplinasIdRoute
  '/app/disciplinas/': typeof AppDisciplinasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/notas': typeof AppNotasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app': typeof AppIndexRoute
  '/app/disciplinas/$id': typeof AppDisciplinasIdRoute
  '/app/disciplinas': typeof AppDisciplinasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/biblioteca': typeof AppBibliotecaRoute
  '/app/calendario': typeof AppCalendarioRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/notas': typeof AppNotasRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/solicitacoes': typeof AppSolicitacoesRoute
  '/app/suporte': typeof AppSuporteRoute
  '/app/': typeof AppIndexRoute
  '/app/disciplinas/$id': typeof AppDisciplinasIdRoute
  '/app/disciplinas/': typeof AppDisciplinasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/biblioteca'
    | '/app/calendario'
    | '/app/financeiro'
    | '/app/notas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/solicitacoes'
    | '/app/suporte'
    | '/app/'
    | '/app/disciplinas/$id'
    | '/app/disciplinas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/biblioteca'
    | '/app/calendario'
    | '/app/financeiro'
    | '/app/notas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/solicitacoes'
    | '/app/suporte'
    | '/app'
    | '/app/disciplinas/$id'
    | '/app/disciplinas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/biblioteca'
    | '/app/calendario'
    | '/app/financeiro'
    | '/app/notas'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/solicitacoes'
    | '/app/suporte'
    | '/app/'
    | '/app/disciplinas/$id'
    | '/app/disciplinas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/solicitacoes': {
      id: '/app/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/app/solicitacoes'
      preLoaderRoute: typeof AppSolicitacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas': {
      id: '/app/notas'
      path: '/notas'
      fullPath: '/app/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendario': {
      id: '/app/calendario'
      path: '/calendario'
      fullPath: '/app/calendario'
      preLoaderRoute: typeof AppCalendarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/biblioteca': {
      id: '/app/biblioteca'
      path: '/biblioteca'
      fullPath: '/app/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disciplinas/': {
      id: '/app/disciplinas/'
      path: '/disciplinas'
      fullPath: '/app/disciplinas/'
      preLoaderRoute: typeof AppDisciplinasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disciplinas/$id': {
      id: '/app/disciplinas/$id'
      path: '/disciplinas/$id'
      fullPath: '/app/disciplinas/$id'
      preLoaderRoute: typeof AppDisciplinasIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppCalendarioRoute: typeof AppCalendarioRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppNotasRoute: typeof AppNotasRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSolicitacoesRoute: typeof AppSolicitacoesRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDisciplinasIdRoute: typeof AppDisciplinasIdRoute
  AppDisciplinasIndexRoute: typeof AppDisciplinasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppCalendarioRoute: AppCalendarioRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppNotasRoute: AppNotasRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSolicitacoesRoute: AppSolicitacoesRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
  AppDisciplinasIdRoute: AppDisciplinasIdRoute,
  AppDisciplinasIndexRoute: AppDisciplinasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
